# generator/cv_builder.py
import os
import json
import re
from openai import OpenAI
from anthropic import Anthropic
from generator.config import OPENAI_API_KEY, ANTHROPIC_API_KEY, SYSTEM_PROMPT, LINKEDIN_PROFILE

# Initialize API clients
openai_client = OpenAI(api_key=OPENAI_API_KEY)
anthropic_client = Anthropic(api_key=ANTHROPIC_API_KEY)


# ================================
# Load Base CV
# ================================
def load_base_cv():
    """Load your base CV (used as the only source of truth)."""
    with open("data/base_cv.txt", "r", encoding="utf-8") as f:
        return f.read().strip()


BASE_CV = load_base_cv()


# ================================
# Load Few-Shot Examples (optional)
# ================================
def load_examples():
    try:
        with open("data/examples.json", "r", encoding="utf-8") as f:
            return json.load(f)
    except:
        return []


EXAMPLES = load_examples()


# ================================
# Utility: Clean markdown artifacts
# ================================
def clean(text):
    """Remove markdown bold/italic formatting generated by the model."""
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*", r"\1", text)
    return text.strip()


# ================================
# Build Few-Shot Prompt
# ================================
def build_prompt(job_desc):
    """Build the full user prompt including examples + job description + base CV."""
    fewshot = ""

    for ex in EXAMPLES[:3]:
        fewshot += (
            f"Job Description:\n{ex['job_desc']}\n"
            f"Tailored CV:\n{ex['tailored_cv']}\n\n"
        )

    return (
        f"Examples:\n{fewshot}"
        f"Job Description:\n{job_desc}\n\n"
        f"Base CV:\n{BASE_CV}\n\n"
        "Tailored CV:\n"
        '(After the CV, add a single line exactly like this: '
        '"JOB_FIT_PERCENT: <number between 0 and 100>%" to reflect the match score.)'
    )


# ================================
# Generate CV (HTML + PDF-Safe)
# ================================
FIT_REGEX = re.compile(r"JOB_FIT_PERCENT:\s*(\d{1,3})")


def generate_cv(job_desc, custom_prompt=None, model="gpt-4o"):
    """
    Produce two versions:
    - HTML/TXT version (header with plain text)
    - PDF-safe version (header with <link> tag)

    Args:
        job_desc: Job description text
        custom_prompt: Optional custom system prompt
        model: Model to use (OpenAI or Anthropic, default: "gpt-4o")
    """

    system_prompt = custom_prompt if custom_prompt else SYSTEM_PROMPT
    prompt = build_prompt(job_desc)

    # Determine if this is an Anthropic model
    is_anthropic = model.startswith("claude-")

    if is_anthropic:
        # Anthropic API call
        response = anthropic_client.messages.create(
            model=model,
            max_tokens=4096,
            temperature=0.6,
            system=system_prompt,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        raw_content = response.content[0].text
    else:
        # OpenAI API call
        # Models that only support default temperature (1)
        models_with_fixed_temp = ["gpt-5", "gpt-5-mini", "gpt-5-nano", "gpt-5.1"]

        # Build API call parameters
        api_params = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt},
            ],
        }

        # Only set temperature for models that support custom values
        if model.lower() not in models_with_fixed_temp:
            api_params["temperature"] = 0.6

        response = openai_client.chat.completions.create(**api_params)
        raw_content = response.choices[0].message.content
    job_fit_percent = extract_fit_percent(raw_content)
    content = clean(remove_fit_line(raw_content))

    # Force SUMMARY to appear first
    if not content.upper().startswith("SUMMARY"):
        content = "SUMMARY\n" + content

    # =============================
    # Headers
    # =============================

    # Header for TXT/HTML (plain)
    header_html = (
        "LIRAN ROTH\n"
        "LinkedIn | 0542223310 | liranrothwork@gmail.com\n\n"
    )

    # Header for PDF — MUST be one continuous line (ReportLab hyperlink uses <link>)
    header_pdf = (
        f"<link href='{LINKEDIN_PROFILE}'>LinkedIn</link> | "
        "0542223310 | liranrothwork@gmail.com"
    )

    # Return both versions
    return header_html + content, header_pdf + content, job_fit_percent


def extract_fit_percent(text):
    if not text:
        return None
    match = FIT_REGEX.search(text)
    if not match:
        return None
    value = int(match.group(1))
    return max(0, min(value, 100))


def remove_fit_line(text):
    if not text:
        return ""
    return re.sub(r"^\s*JOB_FIT_PERCENT:.*$", "", text, flags=re.MULTILINE)
